services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    user: "appuser"
    ports:
      - "${BACKEND_PORTS}"
    depends_on:
      - db
    environment:
      FLASK_ENV: ${FLASK_ENV}
      FLASK_DEBUG: 1
      DATABASE_URL: "${DATABASE_URL}"
    env_file:
      - .env

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - .env

volumes:
  postgres_data:
