name: Scrape News Every 13 Minutes

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 13 minutes
  push:
    branches:
      - main
      - develop
      - backend/*

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Scrape
        run: |
          curl -X POST ${{ secrets.BACKEND_URL }}/api/scrape
